/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/about`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/newtrap` | `/newtrap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/repo` | `/repo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/activeMonitoring`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/findings/detail`; params?: Router.UnknownInputParams; } | { pathname: `/findings`; params?: Router.UnknownInputParams; } | { pathname: `/incidentalCapture`; params?: Router.UnknownInputParams; } | { pathname: `/repos`; params?: Router.UnknownInputParams; } | { pathname: `/repos/repodetail`; params?: Router.UnknownInputParams; } | { pathname: `/routineInspection`; params?: Router.UnknownInputParams; } | { pathname: `/traps/detail`; params?: Router.UnknownInputParams; } | { pathname: `/traps`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/about`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/newtrap` | `/newtrap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/repo` | `/repo`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/activeMonitoring`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/register`; params?: Router.UnknownOutputParams; } | { pathname: `/findings/detail`; params?: Router.UnknownOutputParams; } | { pathname: `/findings`; params?: Router.UnknownOutputParams; } | { pathname: `/incidentalCapture`; params?: Router.UnknownOutputParams; } | { pathname: `/repos`; params?: Router.UnknownOutputParams; } | { pathname: `/repos/repodetail`; params?: Router.UnknownOutputParams; } | { pathname: `/routineInspection`; params?: Router.UnknownOutputParams; } | { pathname: `/traps/detail`; params?: Router.UnknownOutputParams; } | { pathname: `/traps`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/about${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/newtrap${`?${string}` | `#${string}` | ''}` | `/newtrap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/repo${`?${string}` | `#${string}` | ''}` | `/repo${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/activeMonitoring${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/register${`?${string}` | `#${string}` | ''}` | `/findings/detail${`?${string}` | `#${string}` | ''}` | `/findings${`?${string}` | `#${string}` | ''}` | `/incidentalCapture${`?${string}` | `#${string}` | ''}` | `/repos${`?${string}` | `#${string}` | ''}` | `/repos/repodetail${`?${string}` | `#${string}` | ''}` | `/routineInspection${`?${string}` | `#${string}` | ''}` | `/traps/detail${`?${string}` | `#${string}` | ''}` | `/traps${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/about`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/newtrap` | `/newtrap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/repo` | `/repo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/activeMonitoring`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/findings/detail`; params?: Router.UnknownInputParams; } | { pathname: `/findings`; params?: Router.UnknownInputParams; } | { pathname: `/incidentalCapture`; params?: Router.UnknownInputParams; } | { pathname: `/repos`; params?: Router.UnknownInputParams; } | { pathname: `/repos/repodetail`; params?: Router.UnknownInputParams; } | { pathname: `/routineInspection`; params?: Router.UnknownInputParams; } | { pathname: `/traps/detail`; params?: Router.UnknownInputParams; } | { pathname: `/traps`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
